#######################
# dotfiles ############
#######################
source $DOTFILES/mathias/.exports
source $DOTFILES/mathias/.functions
source $DOTFILES/mathias/.aliases

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#######################
# other stuff #########
#######################

# increase socket limit (open files)
ulimit -n 1200

# rbenv to enable shims and auto-complete
eval "$(rbenv init -)"

export DOCKER_HOST=localhost
