# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# if we haven't sourced the general config, do it
if not set -q __fish_general_config_sourced

    set --prepend fish_function_path /nix/store/cpjabgjm9pvdvjc3qz2xzwfbadhdna49-fishplugin-foreign-env-git-20200209/share/fish/vendor_functions.d
    fenv source /home/schickling/.nix-profile/etc/profile.d/hm-session-vars.sh >/dev/null
    set -e fish_function_path[1]


    # and leave a note so we don't source this config section again from
    # this very shell (children will source the general config anew)
    set -g __fish_general_config_sourced 1

end

# if we haven't sourced the login config, do it
status --is-login; and not set -q __fish_login_config_sourced
and begin

    # Login shell initialisation


    # and leave a note so we don't source this config section again from
    # this very shell (children will source the general config anew)
    set -g __fish_login_config_sourced 1

end

# if we haven't sourced the interactive config, do it
status --is-interactive; and not set -q __fish_interactive_config_sourced
and begin

    # Abbreviations


    # Aliases


    # Prompt initialisation


    # Interactive shell intialisation
    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/schickling/.local/share/fish/home-manager_generated_completions" $post
    end


    # and leave a note so we don't source this config section again from
    # this very shell (children will source the general config anew,
    # allowing configuration changes in, e.g, aliases, to propagate)
    set -g __fish_interactive_config_sourced 1

end
